### ISSUE TITLE
Usage with CRNA

### ISSUE THREAD

**Issue by SirPhemmiey** [andela-Jaderibigbe/RavePaymentGateWay#1]
Hello @andela-Jaderibigbe , Please how can i use this module with create-react-native-app? It appears i have to use react-native-link which isn't supported with CRNA. What workaround could i do?

**Comment by heyolajyd** [comment]
Hey Akinde,

I am currently working on an update. For now you just have to eject the application to make the crypto module available in your RN environment. CRNA doesn’t support it just yet so you’ll have to eject the application. Hope this helps. Let me know if you have any issues.

**Comment by ekeneduru** [comment]
helle @andela-Jaderibigbe  Please can you explain why an having this issue.  rn-nodeify --hack --install
module.js:540
    throw err;
    ^

Error: Cannot find module 'C:\Rave\AwesomeProject\node_modules\.bin\package.json'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Rave\AwesomeProject\node_modules\rn-nodeify\cmd.js:18:11)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by ekeneduru** [comment]
And again do i need to clone you source and copy src. How do i know when the payment is successful. i mean response return by Rave.

**Comment by ekeneduru** [comment]
And again how to use sandbox account for this. Your help we be highly appreciated .

**Comment by heyolajyd** [comment]
@ekeneduru its simple the reason why we're using the `rn-nodeify --hack --install` is simply to reimplement node's crypto module so that it can run in react-native supported environments.

**Comment by ekeneduru** [comment]
@andela-Jaderibigbe What is the cause off the error i added above.
